on:
    issues:
        types: [opened]

jobs:
    comment-and-close:
        runs-on: ubuntu-latest
        steps:
            - uses: vardevs/candc@v1
              with:
                  close-comment: 'If you would like to file a bug report or feature request, please refer to our issue tracker: https://jira.dhis2.org'
                  exempt-users: dhis2-bot
                  github-token: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
